[package]
name = "neural_network_handwriting"
version = "0.1.0"
authors = ["Gareth Charnock <gareth.charnock@zerolight.com>"]

[dependencies]

byteorder = "1.2.3"
rand = "0.4.2"
num-traits = "0.2.4"

[dev-dependencies]
assert_approx_eq = "1.0.0"
